version: 2
sphinx:
  configuration: docs/conf.py
build:
  image: latest
python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - yaml
        - lsp
    - requirements: docs/requirements.txt
