#!/usr/bin/env python3
# coding: utf-8

import argparse

from cp2k_input.parser import CP2KInputParser


def key_trafo(string):
    if len(string) <= 3:
        return string.upper()

    return string.lower()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Convert CP2K input to JSON (default) or YAML"
    )
    parser.add_argument("file", metavar="<file>", type=str, help="CP2K input file")
    parser.add_argument("-y", "--yaml", action="store_true")
    args = parser.parse_args()

    cp2k_parser = CP2KInputParser("cp2k_input.xml", key_trafo=key_trafo)

    with open(args.file, "r") as fhandle:
        tree = cp2k_parser.parse(fhandle)

    if args.yaml:
        import yaml

        print(yaml.dump(tree, indent=2))
    else:
        import json

        print(json.dumps(tree, indent=2))
