name: deploy

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install poetry==1.1.6
    - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
    - run: poetry publish --build
