name: deploy

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: snok/install-poetry@v1.3.4
    - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
    - run: poetry publish --build
